# Integrate ML module for predictions

In [1]:
import sys
sys.path.append('../absenteeism')
from main import *

with open('../absenteeism/model','rb') as model_file, open('../absenteeism/scaler', 'rb') as scaler_file:
    model = pickle.load(model_file)
    scaler = pickle.load(scaler_file)
ml = absenteeism_model(model,scaler)

df = ml.load_and_clean_data('../absenteeism/data/Absenteeism_new_data.csv')

df_new_obs = ml.predicted_outputs()

df_new_obs

,reason 1,reason 2,reason 3,reason 4,Education,Transportation Expense,Age,Body Mass Index,Children,Pets,Month,Probability,Prediction
0,1,0.0,0.0,0.0,1,179,30,19,0,0,6,0.578747,1
1,1,0.0,0.0,0.0,0,361,28,27,1,4,6,0.756194,1
2,1,0.0,0.0,0.0,0,155,34,25,2,0,6,0.722781,1
3,1,0.0,0.0,0.0,1,179,40,22,2,0,6,0.688075,1
4,1,0.0,0.0,0.0,0,155,34,25,2,0,6,0.722781,1
5,1,0.0,0.0,0.0,0,225,28,24,1,2,6,0.656427,1
6,1,0.0,0.0,0.0,0,118,46,25,2,0,6,0.608660,1
7,1,0.0,0.0,0.0,1,179,30,19,0,0,6,0.578747,1
8,1,0.0,0.0,0.0,0,118,37,28,0,0,6,0.534579,1
9,1,0.0,0.0,0.0,0,118,37,28,0,0,6,0.534579,1
10,1,0.0,0.0,0.0,0,378,36,21,2,4,6,0.768605,1
11,1,0.0,0.0,0.0,0,118,50,31,1,0,6,0.565855,1
12,1,0.0,0.0,0.0,1,233,31,21,1,8,6,0.182578,0
13,1,0.0,0.0,0.0,1,179,30,19,0,0,6,0.578747,1
14,0,0.0,0.0,0.0,0,235,48,33,1,5,6,0.054303,0
15,0,0.0,0.0,0.0,1,268,33,25,0,0,6,0.199322,0
16,1,0.0,0.0,0.0,0,118,50,31,1,0,6,0.565855,1
17,1,0.0,0.0,0.0,1,179,30,19,0,0,6,0.578747,1
18,1,0.0,0.0,0.0,0,291,40,25,1,1,6,0.779209,1
19,1,0.0,0.0,0.0,1,179,30,19,0,0,7,0.585317,1
20,1,0.0,0.0,0.0,0,118,37,28,0,0,7,0.541292,1
21,1,0.0,0.0,0.0,1,233,31,21,1,8,7,0.186644,0
22,1,0.0,0.0,0.0,0,118,37,28,0,0,7,0.541292,1
23,1,0.0,0.0,0.0,0,118,37,28,0,0,7,0.541292,1
24,1,0.0,0.0,0.0,1,233,31,21,1,8,7,0.186644,0
25,1,0.0,0.0,0.0,0,235,43,38,1,0,7,0.822994,1
26,1,0.0,0.0,0.0,1,233,31,21,1,8,7,0.186644,0
27,1,0.0,0.0,0.0,0,228,58,22,2,1,7,0.656845,1
28,1,0.0,0.0,0.0,0,118,37,28,0,0,7,0.541292,1
29,1,0.0,0.0,0.0,0,228,58,22,2,1,7,0.656845,1
30,1,0.0,0.0,0.0,0,189,33,25,2,2,7,0.650913,1
31,1,0.0,0.0,0.0,0,118,37,28,0,0,7,0.541292,1
32,1,0.0,0.0,0.0,0,361,28,27,1,4,7,0.761139,1
33,1,0.0,0.0,0.0,0,225,28,24,1,2,7,0.662493,1
34,1,0.0,0.0,0.0,0,369,31,25,3,0,7,0.950307,1
35,1,0.0,0.0,0.0,0,289,33,30,2,1,7,0.864989,1
36,1,0.0,0.0,0.0,1,235,37,29,1,1,7,0.714063,1
37,0,0.0,0.0,0.0,0,118,40,34,1,8,7,0.011158,0
38,0,0.0,0.0,0.0,0,231,39,35,2,2,7,0.202127,0
39,0,0.0,0.0,0.0,0,179,53,25,1,1,7,0.088853,0

# Connect to mySQL

In [2]:
import pymysql

In [13]:
conn = pymysql.connect(database = 'predicted_outputs', user = 'root', password = 'root')

In [14]:
cursor = conn.cursor()

In [15]:
cursor.execute('SELECT * FROM predicted_outputs;')

0

# Creating INSERT statement

In [6]:
df_new_obs.shape

(40, 13)

In [7]:
insert_query = 'INSERT INTO predicted_outputs VALUES '
insert_query

'INSERT INTO predicted_outputs VALUES '

In [8]:
df_new_obs.columns.values

array(['reason 1', 'reason 2', 'reason 3', 'reason 4', 'Education',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Children',
       'Pets', 'Month', 'Probability', 'Prediction'], dtype=object)

In [9]:
for i in range(df_new_obs.shape[0]):
    insert_query += '('
    for j in range(df_new_obs.shape[1]):
        insert_query += str(df_new_obs[df_new_obs.columns.values[j]][i]) + ', '
        
    insert_query = insert_query [:-2] + '), '

insert_query = insert_query[:-2] + ', '
insert_query = insert_query[:-2] + ';'

In [10]:
insert_query

'INSERT INTO predicted_outputs VALUES (1, 0.0, 0.0, 0.0, 1, 179, 30, 19, 0, 0, 6, 0.5787467375289725, 1), (1, 0.0, 0.0, 0.0, 0, 361, 28, 27, 1, 4, 6, 0.7561944705719084, 1), (1, 0.0, 0.0, 0.0, 0, 155, 34, 25, 2, 0, 6, 0.7227813473720155, 1), (1, 0.0, 0.0, 0.0, 1, 179, 40, 22, 2, 0, 6, 0.6880752478210386, 1), (1, 0.0, 0.0, 0.0, 0, 155, 34, 25, 2, 0, 6, 0.7227813473720155, 1), (1, 0.0, 0.0, 0.0, 0, 225, 28, 24, 1, 2, 6, 0.656427310746459, 1), (1, 0.0, 0.0, 0.0, 0, 118, 46, 25, 2, 0, 6, 0.6086600257295651, 1), (1, 0.0, 0.0, 0.0, 1, 179, 30, 19, 0, 0, 6, 0.5787467375289725, 1), (1, 0.0, 0.0, 0.0, 0, 118, 37, 28, 0, 0, 6, 0.5345786735731438, 1), (1, 0.0, 0.0, 0.0, 0, 118, 37, 28, 0, 0, 6, 0.5345786735731438, 1), (1, 0.0, 0.0, 0.0, 0, 378, 36, 21, 2, 4, 6, 0.7686048697857822, 1), (1, 0.0, 0.0, 0.0, 0, 118, 50, 31, 1, 0, 6, 0.5658552564150587, 1), (1, 0.0, 0.0, 0.0, 1, 233, 31, 21, 1, 8, 6, 0.18257840555917504, 0), (1, 0.0, 0.0, 0.0, 1, 179, 30, 19, 0, 0, 6, 0.5787467375289725, 1), (0, 0.0, 0.0, 0.0, 0, 235, 48, 33, 1, 5, 6, 0.054302788812890614, 0), (0, 0.0, 0.0, 0.0, 1, 268, 33, 25, 0, 0, 6, 0.19932157758706007, 0), (1, 0.0, 0.0, 0.0, 0, 118, 50, 31, 1, 0, 6, 0.5658552564150587, 1), (1, 0.0, 0.0, 0.0, 1, 179, 30, 19, 0, 0, 6, 0.5787467375289725, 1), (1, 0.0, 0.0, 0.0, 0, 291, 40, 25, 1, 1, 6, 0.7792089757351826, 1), (1, 0.0, 0.0, 0.0, 1, 179, 30, 19, 0, 0, 7, 0.585317089721827, 1), (1, 0.0, 0.0, 0.0, 0, 118, 37, 28, 0, 0, 7, 0.5412919106463655, 1), (1, 0.0, 0.0, 0.0, 1, 233, 31, 21, 1, 8, 7, 0.18664390673322492, 0), (1, 0.0, 0.0, 0.0, 0, 118, 37, 28, 0, 0, 7, 0.5412919106463655, 1), (1, 0.0, 0.0, 0.0, 0, 118, 37, 28, 0, 0, 7, 0.5412919106463655, 1), (1, 0.0, 0.0, 0.0, 1, 233, 31, 21, 1, 8, 7, 0.18664390673322492, 0), (1, 0.0, 0.0, 0.0, 0, 235, 43, 38, 1, 0, 7, 0.8229935806408768, 1), (1, 0.0, 0.0, 0.0, 1, 233, 31, 21, 1, 8, 7, 0.18664390673322492, 0), (1, 0.0, 0.0, 0.0, 0, 228, 58, 22, 2, 1, 7, 0.6568445089247656, 1), (1, 0.0, 0.0, 0.0, 0, 118, 37, 28, 0, 0, 7, 0.5412919106463655, 1), (1, 0.0, 0.0, 0.0, 0, 228, 58, 22, 2, 1, 7, 0.6568445089247656, 1), (1, 0.0, 0.0, 0.0, 0, 189, 33, 25, 2, 2, 7, 0.6509133216330933, 1), (1, 0.0, 0.0, 0.0, 0, 118, 37, 28, 0, 0, 7, 0.5412919106463655, 1), (1, 0.0, 0.0, 0.0, 0, 361, 28, 27, 1, 4, 7, 0.7611394209109466, 1), (1, 0.0, 0.0, 0.0, 0, 225, 28, 24, 1, 2, 7, 0.6624926326518797, 1), (1, 0.0, 0.0, 0.0, 0, 369, 31, 25, 3, 0, 7, 0.9503074424840229, 1), (1, 0.0, 0.0, 0.0, 0, 289, 33, 30, 2, 1, 7, 0.8649888314453745, 1), (1, 0.0, 0.0, 0.0, 1, 235, 37, 29, 1, 1, 7, 0.7140627873501673, 1), (0, 0.0, 0.0, 0.0, 0, 118, 40, 34, 1, 8, 7, 0.011157624880658124, 0), (0, 0.0, 0.0, 0.0, 0, 231, 39, 35, 2, 2, 7, 0.20212656778314506, 0), (0, 0.0, 0.0, 0.0, 0, 179, 53, 25, 1, 1, 7, 0.08885309479758058, 0);'

In [16]:
cursor.execute(insert_query)

40

In [17]:
conn.commit()